use_frameworks!

target 'DynamicBinder_Example' do
  platform :ios, '8.0'
  pod 'DynamicBinder', :path => '../'

  target 'DynamicBinder_Tests' do
    inherit! :search_paths
    #pod 'Quick', '~> 1.0.0'
    #pod 'Nimble', '~> 5.1.1'
  end
end
